title: Kavya Baltha
logo: /IMG_5240-modified.png
theme: jekyll-theme-minimal
description: |
  
  Data Scientist with 4+ years of commercial experience in analytics, strategy, and sales 
  and a master's degree in Data Science from Oxford University. 
  Previously at Vodafone, VIMA Group (management consulting), Ovo Energy, HSBC.
